### ISSUE TITLE
when I require third module, I always receive errors

### ISSUE THREAD

**Issue by lovetingyuan** [1backend/1backend#114]
> Get http://127.0.0.1:38893/ping: dial tcp 127.0.0.1:38893: getsockopt: connection refused
![1backend com_tingyuan_test](https://user-images.githubusercontent.com/7310471/35025205-157542ce-fb7f-11e7-855a-d6d3fcdfec58.png)

when I remove require('lodash'), error is gone

**Comment by lovetingyuan** [comment]
I have add dependency "lodash" in `package.json`

**Comment by crufter** [comment]
@lovetingyuan I think you have to add it in the package.json as a dependency.

Can you try that please?

**Comment by crufter** [comment]
@lovetingyuan That should work. Can you link to your project, please?

**Comment by lovetingyuan** [comment]
@crufter the link is https://1backend.com/tingyuan/test and the curl command is `curl -XGET https://1backend.com:9993/app/tingyuan/test/name -H 'token: 2d407af7-60b6-418f-a646-c6bad9bd4150'`
thanks.

**Comment by crufter** [comment]
@lovetingyuan We have a "view logs" functionality in master but we haven't shipped it - I logged into the servers and I see the following:

```
> node server.js

module.js:544
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/server.js:7:14)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 1backend-nodejs-service@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 1backend-nodejs-service@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-17T07_27_46_806Z-debug.log
```
 
I had a look at your build logs and it all looks fine. Not sure what's going on but I will keep digging, @lovetingyuan

**Comment by lovetingyuan** [comment]
@crufter thank you a lot, I will remain the api

**Comment by crufter** [comment]
@lovetingyuan You are welcome, and sorry for the inconvenience :) Hopefully we will fix it soon

**Comment by cybrox** [comment]
@crufter While on the topic, I think having the proxy dispatch a clearer error message when the project endpoint is not reachable would be very nice.

Also, looking forward to be able to view logs. I screwed up a dependency in the `package.json` and since I can't clear the deps cache (I assume I can't?) and debugging the current state of `node_modules` is obviously not easily possible without logs, I'm pretty much stuck for now. 😄

**Comment by crufter** [comment]
@cybrox Haha, that's a really interesting situation :D. There are a couple of points that will help in the future:

- 1 click installation so you can easily debug stuff on your local box.
- Moving 1Backend services between installations (so you can deploy something from 1backend.com to your local install easily).
- Although there is integration for github for the generated clients, the service configuration/data itself is not in version control.
- Rollback functionality (perhaps this is a variation of the previous point)
- As you say @cybrox, being able to view logs...

For the time being just create an other service, don't be afraid of littering, projects are woken up on demand so theoretically even a single node supports an practically infinite amount of projects.

**Comment by crufter** [comment]
@lovetingyuan @cybrox We have deployed the View Logs functionality.

**Comment by crufter** [comment]
@lovetingyuan The fix for the lodash problem should be in live now.

**Comment by lovetingyuan** [comment]
@crufter  yes, awesome, thanks!
