### ISSUE TITLE
e-mail addresses containing a dash are treated as unvalid when registering.

### ISSUE THREAD

**Issue by thefakewizard** [1backend/1backend#115]
Other email addresses without dashes are instead treated as valid.
 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/17289614/35033526-499bb45c-fb6b-11e7-84fd-008094764391.png">

My email address contains a dash. I couldn't register.

**Comment by crufter** [comment]
@thefakewizard Ouch! Sorry about that. We are going to fix it.

**Comment by thefakewizard** [comment]
NP, thanks for the immediate reply 😄

**Comment by crufter** [comment]
@thefakewizard Fixed and deployed by @Dobika in #123
